"""A2A Agent Card emitter.

The A2A specification is now canonically a Protobuf definition; the JSON Schema
published alongside it is explicitly a non-normative build artifact. So the card
emitted here follows the `AgentCard` message shape from `specification/a2a.proto`
rather than a schema that may be regenerated underneath us.

Every card carries `"unofficial": true` and an explicit provenance block. It is
generated, unsigned, and describes a site we do not represent — implying
otherwise would be the single most misleading thing this project could ship.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from typing import Any

from wasl.graph.state import Capability

A2A_PROTOCOL_VERSION = "0.3"


def build_agent_card(
    *,
    capabilities: list[Capability],
    domain: str,
    site_name: str,
    server_name: str,
    wasl_score: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Build an Agent Card from accepted capabilities.

    Skills map 1:1 from accepted capabilities. A capability the critic rejected
    does not become a skill, which means the card and the "what we refused to
    generate" panel are always consistent with each other.
    """
    skills = [
        {
            "id": capability.tool_schema.name if capability.tool_schema else capability.name,
            "name": capability.description[:80] or capability.name,
            "description": capability.description,
            "tags": [capability.verb, capability.noun.replace(" ", "_")],
            "examples": [f"{capability.verb} {capability.noun} on {domain}"],
            "inputModes": ["text/plain", "application/json"],
            "outputModes": ["text/plain", "application/json"],
            # Not part of the A2A schema — Wasl's own provenance, namespaced so
            # it cannot be mistaken for a spec field.
            "x-wasl-evidence": capability.evidence_ids,
        }
        for capability in capabilities
        if capability.accepted
    ]

    return {
        "protocolVersion": A2A_PROTOCOL_VERSION,
        "name": f"{site_name} (unofficial, generated)",
        "description": (
            f"Read-only agent interface to public content on {domain}, generated by "
            f"Wasl AI from evidence in that site's public markup. Not published or "
            f"endorsed by {site_name}."
        ),
        "url": f"https://{domain}",
        "version": "0.1.0",
        "provider": {
            "organization": "Wasl AI (generated artifact)",
            "url": "https://github.com/",
        },
        "capabilities": {
            "streaming": False,
            "pushNotifications": False,
            "stateTransitionHistory": False,
        },
        "defaultInputModes": ["text/plain", "application/json"],
        "defaultOutputModes": ["text/plain", "application/json"],
        # v1 generates nothing authenticated. Stated explicitly rather than omitted.
        "securitySchemes": {},
        "security": [],
        "skills": skills,
        "x-wasl": {
            "unofficial": True,
            "signed": False,
            "generated_at": datetime.now(UTC).isoformat(),
            "generated_by": "Wasl AI",
            "server_name": server_name,
            "read_only": True,
            "state_changing_capabilities_detected": [
                capability.name
                for capability in capabilities
                if capability.implies_state_change()
            ],
            "wasl_score": wasl_score or {},
            "disclaimer": (
                "This Agent Card is generated, unsigned and illustrative. It is not a "
                "registered production agent, it was not published by the site it "
                "describes, and it should not be treated as an endorsement or as an "
                "official integration point."
            ),
        },
    }


def render(card: dict[str, Any]) -> str:
    return json.dumps(card, indent=2, ensure_ascii=False) + "\n"
