"""llms.txt emitter.

Follows the community convention: H1 site name, a blockquote summary, then linked
sections. What Wasl emits is a *proposal* — a file the site owner could adopt —
so it is written in their voice and describes their content, not ours.

It is built only from evidence actually collected. Inventing plausible sections a
site "probably" has would make the file worse than useless: an llms.txt that
promises pages which do not exist teaches an agent to distrust the whole
convention.
"""

from __future__ import annotations

from urllib.parse import urlparse

from wasl.crawler.evidence import EvidenceStore
from wasl.graph.state import Capability, PageSummary


def _title_from(url: str) -> str:
    path = urlparse(url).path.strip("/")
    if not path:
        return "Home"
    return path.split("/")[-1].replace("-", " ").replace("_", " ").title()


def build_llms_txt(
    *,
    site_name: str,
    domain: str,
    capabilities: list[Capability],
    pages: list[PageSummary],
    store: EvidenceStore | None = None,
    description: str | None = None,
) -> str:
    """Render a proposed llms.txt for a site."""
    lines: list[str] = [f"# {site_name}", ""]

    summary = description or (
        f"Public content on {domain}. This file is a proposal generated by Wasl AI "
        f"from the site's own markup; it has not been published by {site_name}."
    )
    lines += [f"> {summary}", ""]

    accepted = [c for c in capabilities if c.accepted]
    if accepted:
        lines += ["## What an agent can do here", ""]
        for capability in accepted:
            lines.append(f"- **{capability.verb} {capability.noun}**: {capability.description}")
        lines.append("")

    # Only real, successfully-fetched pages. No invented sections.
    readable = [p for p in pages if p.ok and not p.robots_blocked]
    if readable:
        lines += ["## Pages", ""]
        for page in readable[:25]:
            lines.append(f"- [{_title_from(page.final_url)}]({page.final_url})")
        lines.append("")

    if store is not None:
        specs = [e for e in store.by_kind("openapi") if e.selector == "openapi#spec"]
        if specs:
            lines += ["## API", ""]
            for evidence in specs[:5]:
                lines.append(f"- [OpenAPI specification]({evidence.source_url})")
            lines.append("")

    detected = [c for c in capabilities if c.implies_state_change()]
    if detected:
        lines += [
            "## Not exposed",
            "",
            "These were detected but are deliberately not offered as agent operations, "
            "because they change state on a system Wasl does not control:",
            "",
        ]
        for capability in detected:
            lines.append(f"- {capability.verb} {capability.noun}")
        lines.append("")

    lines += [
        "---",
        "",
        f"Generated by Wasl AI from a read-only crawl of {domain}. "
        "Every entry above corresponds to content that was actually fetched — "
        "nothing here is inferred or invented.",
        "",
    ]

    return "\n".join(lines)
