"""Assemble and package the generated artifacts.

The order here is the point: **generate, verify, then package.** The ZIP is only
written after a clean subprocess has imported the server and listed its tools, so
there is no code path that offers an unverified download.
"""

from __future__ import annotations

import hashlib
import json
import logging
import zipfile
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from wasl.crawler.evidence import EvidenceStore
from wasl.generators.agent_card import build_agent_card, render as render_card
from wasl.generators.llms_txt import build_llms_txt
from wasl.generators.mcp_server import generate_server, safe_identifier
from wasl.generators.verify import VerificationResult, verify_server
from wasl.graph.state import Capability, GeneratedArtifacts, PageSummary

logger = logging.getLogger(__name__)

README_TEMPLATE = """# {site_name} — generated MCP server

Generated by [Wasl AI]({repo}) on {date} from a read-only crawl of `{domain}`.

**This is unofficial.** {site_name} did not publish it and has not endorsed it.
It demonstrates what an agent-readable interface to their public content could
look like, built from evidence in their own markup.

## Wasl score

{score_block}

## What it does

{tool_block}

Every tool is **read-only** and reads from a **cached snapshot** taken during the
crawl. Running this server sends no requests to `{domain}`.

Wasl does not generate state-changing tools for sites it does not control.
{refused_block}

## Install

```bash
pip install "mcp[cli]"
python server.py
```

## Claude Desktop

```json
{{
  "mcpServers": {{
    "{server_name}": {{
      "command": "python",
      "args": ["{abs_hint}/server.py"]
    }}
  }}
}}
```

## Verification

This server was imported in a clean subprocess and its tools introspected before
being offered for download:

```
{verification}
```

## Files

- `server.py` — the FastMCP server
- `snapshot.json` — the cached crawl it reads from
- `agent-card.json` — A2A Agent Card (generated, unsigned, illustrative)
- `llms.txt` — a proposed llms.txt for `{domain}`
- `pyproject.toml` — dependencies

## Provenance

Every tool docstring carries an `EVIDENCE:` block naming the evidence IDs the
capability was induced from. Those IDs resolve to verbatim snippets in the Wasl
report — the score and the tools trace back to the same markup.
"""

PYPROJECT_TEMPLATE = """[project]
name = "{package_name}"
version = "0.1.0"
description = "Generated MCP server for {domain} (unofficial, by Wasl AI)"
requires-python = ">=3.11"
dependencies = ["mcp[cli]>=1.2", "pydantic>=2.9"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
"""


@dataclass(slots=True)
class GenerationOutcome:
    artifacts: GeneratedArtifacts
    verification: VerificationResult
    directory: Path

    @property
    def shipped(self) -> bool:
        return self.verification.ships


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _snapshot_records(store: EvidenceStore, pages: list[PageSummary]) -> list[dict[str, Any]]:
    """Flatten evidence into records the generated tools can search.

    Deliberately built from evidence rather than raw HTML: these are the same
    snippets the score cites, so a tool result and a sub-score point at the same
    bytes.
    """
    records: list[dict[str, Any]] = []
    for evidence in store:
        if evidence.kind in {"rendering", "media", "injection", "header"}:
            continue
        records.append(
            {
                "id": evidence.id,
                "kind": evidence.kind,
                "url": evidence.source_url,
                "selector": evidence.selector,
                "content": evidence.raw[:2000],
            }
        )
    return records


async def generate_all(
    *,
    job_id: str,
    domain: str,
    site_name: str,
    capabilities: list[Capability],
    pages: list[PageSummary],
    store: EvidenceStore,
    score: dict[str, Any] | None,
    output_root: Path,
) -> GenerationOutcome:
    """Generate, verify, then package. Nothing ships unverified."""
    directory = Path(output_root) / job_id
    directory.mkdir(parents=True, exist_ok=True)

    accepted = [c for c in capabilities if c.accepted]
    server_name = safe_identifier(domain.replace(".", "_")) + "_mcp"

    score_line = (
        f"{score['total']}/{score['max_possible']} ({score.get('band') or 'band suppressed'})"
        if score
        else "not scored"
    )

    # --- generate ------------------------------------------------------------
    source, snapshot = generate_server(
        capabilities=accepted,
        domain=domain,
        site_name=site_name,
        score_line=score_line,
        snapshot_records=_snapshot_records(store, pages),
    )
    server_path = directory / "server.py"
    server_path.write_text(source)
    (directory / "snapshot.json").write_text(snapshot)

    card = build_agent_card(
        capabilities=capabilities,
        domain=domain,
        site_name=site_name,
        server_name=server_name,
        wasl_score=score,
    )
    card_path = directory / "agent-card.json"
    card_path.write_text(render_card(card))

    llms_path = directory / "llms.txt"
    llms_path.write_text(
        build_llms_txt(
            site_name=site_name,
            domain=domain,
            capabilities=capabilities,
            pages=pages,
            store=store,
        )
    )

    (directory / "pyproject.toml").write_text(
        PYPROJECT_TEMPLATE.format(
            package_name=safe_identifier(domain.replace(".", "_")) + "_mcp", domain=domain
        )
    )

    # --- verify --------------------------------------------------------------
    verification = await verify_server(server_path)
    logger.info("verification of %s: %s", server_path, "PASS" if verification.ships else "FAIL")

    refused = [c for c in capabilities if not c.accepted]
    (directory / "README.md").write_text(
        README_TEMPLATE.format(
            site_name=site_name,
            domain=domain,
            server_name=server_name,
            repo="https://github.com/",
            date=datetime.now(UTC).strftime("%Y-%m-%d"),
            abs_hint="/absolute/path/to/this/directory",
            score_block=score_line,
            tool_block=(
                "\n".join(
                    f"- `{t['name']}` — {t.get('description', '').splitlines()[0][:120]}"
                    for t in verification.tools
                )
                or "_No tools were generated — every candidate was refused by the critic._"
            ),
            refused_block=(
                "\n\n### What was refused\n\n"
                + "\n".join(f"- **{c.name}** — see the Wasl report for the reason" for c in refused)
                if refused
                else ""
            ),
            verification=verification.summary(),
        )
    )

    # --- package (only if verified) -----------------------------------------
    zip_path: Path | None = None
    if verification.ships:
        zip_path = directory / f"wasl-{safe_identifier(domain.replace('.', '-'))}.zip"
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as archive:
            for name in (
                "server.py",
                "snapshot.json",
                "agent-card.json",
                "llms.txt",
                "pyproject.toml",
                "README.md",
            ):
                archive.write(directory / name, arcname=name)
    else:
        logger.warning(
            "not packaging %s — verification failed:\n%s", domain, verification.summary()
        )

    return GenerationOutcome(
        artifacts=GeneratedArtifacts(
            server_path=str(server_path),
            agent_card_path=str(card_path),
            llms_txt_path=str(llms_path),
            zip_path=str(zip_path) if zip_path else None,
            tool_count=verification.tool_count,
            verified=verification.ships,
            verification_output=verification.summary(),
        ),
        verification=verification,
        directory=directory,
    )
